### ISSUE TITLE
How to enable the toc permanently

### ISSUE THREAD

**Issue by Pantos** [ether/ep_table_of_contents#30]
Hello,
is there a setting to enable the toc permanently (so you don't have to choose this in the settings first)?

Thanks for your help!

**Comment by x8-999-github** [comment]
Hi,

I am looking for the same. Having had a quick look at the code I do not thinks this is currently possible but of course should not be to hard to fix.

One thing i "discovered" is that you can set toc=true in the url param to enable the toc 
e.g. myurl/p/Item?toc=true

**Comment by guakamole** [comment]
Hello,

Thank you for this great extension :+1: 
Same question here, is there a way to display the ToC by default for all the pads without having to provide a URL ending with "?toc=true" ?

**Comment by Ptrph** [comment]
Hello,
For future information or if anyone still looking for the same issue, I found [this](https://github.com/JohnMcLear/ep_table_of_contents/issues/15). It works for me.

**Comment by fwolfst** [comment]
Put the following in `settings.json`:
```json
"ep_toc": {
  "disable_by_default": false
},
```

**Comment by diesocke** [comment]
I put it at the end of the settings.json. If I save from the admin settings, I get a warning: "YOUR JSON IS BAD AND YOU SHOULD FEEL BAD." If I change the file via FTP it doesn't even display the contents of the file anymore, until I reverse it.

**Comment by JohnMcLear** [comment]
@diesocke remove the trailing ``,`` and before you submit your JSON run it through a JSON validator.  TLDR is you suck at JSON yea you totally suck :D

Seriously tho, it's hard/fiddly for a newcomer to understand JSON but once you get it, it's easy.... <3

**Comment by diesocke** [comment]
I got it working. At least, there is now a tab called "Gliederung" (which is "structure" in German). How do I mark headings to be displayed there?

**Comment by JohnMcLear** [comment]
@diesocke ??  click that select, click an option in that select, they will show up in TOC on the left...

**Comment by diesocke** [comment]
![image](https://user-images.githubusercontent.com/7019947/97008518-37515000-1543-11eb-80f9-65ceeca81364.png)

Which select? I cannot see any, even if I mark some content.
