### ISSUE TITLE
Problem : Titles are truncated in the TOC

### ISSUE THREAD

**Issue by fabrice-noel** [ether/ep_table_of_contents#45]
I just installed this great plugin that you developed (ep_table_of_content v 0.2.3) and that allows to have a table of contents within a PAD.

I have a little problem concerning the display (Firefox v 81.02 - the same pb with Chromium) in the sense that the titles (in the TOC) are truncated as you can see in the screenshot below or directly on the PAD by [clicking here](https://pad.nfcg.tv/p/test). Is there a particular setting to make? If yes, where?

Thank you very much for your help.

Friendly and freely,

Fabrice (Normandy, France)

![Capture du 2020-10-18 10-33-11](https://user-images.githubusercontent.com/69907322/96363321-c6212f80-1133-11eb-848f-f7f61440dd09.png)

#### Server

UbuntuServer 18.04 LTS

#### Etherpad version

Version number: 1.8.6

Latest available version: 1.8.6

Git sha: 3886e95

#### Installed plugins

ep_delete_after_delay
ep_align
ep_author_hover
ep_adminpads2
ep_embedded_hyperlinks2
ep_font_color
ep_etherpad-lite
ep_font_size
ep_spellcheck
ep_pads_stats
ep_headings
ep_table_of_contents

#### Installed parts

ep_table_of_contents/ep_table_of_contents
ep_headings/main
ep_pads_stats/ep_pads_stats
ep_spellcheck/ep_spellcheck
ep_font_size/main
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_font_color/main
ep_embedded_hyperlinks2/main
ep_adminpads2/ep_adminpads2
ep_author_hover/ep_author_hover
ep_align/main
ep_delete_after_delay/ep_delete_after_delay

**Comment by JohnMcLear** [comment]
@seballot any preferred fix here?  I imagine this is expected behaviour but obviously it looks a bit weird.  Do any other plugins use max available horizontal space before pad container I can refer to?

**Comment by seballot** [comment]
Hi ! a bit hard because as the pad is in the iframe, it's not so easy to make all the different column grow as they should
Increasing the size of the TOC will make the pad pulled to the right
![image](https://user-images.githubusercontent.com/17404254/96377793-41accc00-1188-11eb-92db-fe66c0e50306.png)

We could, when the toc is visible, add a class to the editor so we can for example make the left-margin within the editor iframe smaller, so the pad remains more or less in the center. But we need to think of all situations, with different plugins (ep_comments, chat visible and displayed as a sidebar etc...)

maybe we could do some easy fix like
```css
@media (min-width: 1350px) {
#toc { width: 25% }
body.comments-active #toc { width: 20% } // a bit smaller when the comment sidebar is visible
}
```

**Comment by JohnMcLear** [comment]
I put the proposed fix in and published.  Thanks @seballot

**Comment by fabrice-noel** [comment]
I have just upgraded to version 0.2.5 and the result is perfect!

Thanks a lot.

![Capture du 2020-10-23 21-56-55](https://user-images.githubusercontent.com/69907322/97048851-00972c00-157b-11eb-84a0-19ef2e218d5b.png)
