### ISSUE TITLE
Error with etherpad 1.8.7 "Bug in Hook Function"

### ISSUE THREAD

**Issue by meaz** [ether/ep_table_of_contents#49]
Using Etherpad 1.8.7, I get this error in firefox console:
`UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_table_of_contents, function name: ep_table_of_contents/static/js/aceEditEvent:aceEditEvent, hook: aceEditEvent): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior` pointing to this file `ace2_common` line 65.
`

**Comment by JohnMcLear** [comment]
Just a console error.  Not a problem.  It's a core problem and not fixable in the plugin.

**Comment by meaz** [comment]
Do you think I should open a ticket on the main repo then?

**Comment by JohnMcLear** [comment]
If you like but it's just a warning.
