### ISSUE TITLE
Allow URL param to override disable_by_default

### ISSUE THREAD

**Issue by fkohrt** [ether/ep_table_of_contents#52]
For instances where `disable_by_default` is set to `false`, it still would be nice if the URL param `toc=false` would take precedence. From my tests, this is not the case right now, so it is not possible to selectively disable the TOC while having it enabled by default in the `settings.json`.

**Comment by squiddle** [comment]
i am using version 0.3.35 and it is implemented. 

see https://github.com/ether/ep_table_of_contents/blob/7b06116acd312c3270a4672e20c0a8532f4fb721/static/js/postAceInit.js#L29-L37

i guess this issue can be closed or documentation added.

**Comment by fkohrt** [comment]
I can confirm it works as suggested. Good idea to document this, I mention the parameter in the README via #92.
