### ISSUE TITLE
Config option disable_by_default not working

### ISSUE THREAD

**Issue by AlexisAnzieu** [ether/ep_table_of_contents#58]
Hey!
First of all, thanks a lot for your plugin :)

I may have an issue with the settings. I put 
```json
    "ep_toc": {
        "disable_by_default": true
    },
```
to the settings but it seems not working.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/11615615/154736380-c5c1036f-0f33-47f9-ae4a-bc876c60cd89.png">

Did I forget something?

---
Etherpad version: 1.8.16
Running in a docker instance

**Comment by flberger** [comment]
The reason for this misbehaviour is the `urlContainstocTrue` check in `postAceInit.js`. It calls `getParam` in `toc.js`, which checks for `&toc=false` in the URL, and if that's not there, _unconditionally_ enables the toc, not regarding the setting.

The solution that works for me is to comment / remove the whole `urlContainstocTrue` check `postAceInit.js`. That way, the `disable_by_default` setting is respected just fine. Of course the `&toc=false` URL parameter does no longer work after that.

**Comment by flberger** [comment]
Hence, pull request #71 by @FWDekker does _not_ fix the issue.

**Comment by flberger** [comment]
@AlexisAnzieu , a more fitting issue title than "Settings issue" would be "Config option disable_by_default not working". Maybe you could change it?

**Comment by gregcurrie** [comment]
my pull request #119 seems to resolve the issue.
